"""add waveforms table

Revision ID: 61863fd599e4
Revises: 0e7e3563b7fb
Create Date: 2026-07-11 15:41:21.625458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61863fd599e4'
down_revision: Union[str, Sequence[str], None] = '0e7e3563b7fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waveforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('channels', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('sample_rate', sa.Float(), nullable=True),
    sa.Column('n_samples', sa.Integer(), nullable=True),
    sa.Column('n_channels', sa.Integer(), nullable=True),
    sa.Column('segment', sa.String(), nullable=True),
    sa.Column('filters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('data_uri', sa.String(), nullable=False),
    sa.Column('data_format', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['epmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waveforms_id'), 'waveforms', ['id'], unique=False)
    op.create_index(op.f('ix_waveforms_map_id'), 'waveforms', ['map_id'], unique=False)
    op.create_index(op.f('ix_waveforms_study_id'), 'waveforms', ['study_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waveforms_study_id'), table_name='waveforms')
    op.drop_index(op.f('ix_waveforms_map_id'), table_name='waveforms')
    op.drop_index(op.f('ix_waveforms_id'), table_name='waveforms')
    op.drop_table('waveforms')
    # ### end Alembic commands ###
