"""initial schema (multivendor: scalar_fields, vendor, provenance)

Revision ID: 0e7e3563b7fb
Revises: 
Create Date: 2026-07-11 14:13:40.796913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e7e3563b7fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('default_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_attribute_metadata_id'), 'attribute_metadata', ['id'], unique=False)
    op.create_table('colormaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('colors', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('intervals', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('use_gradient', sa.Boolean(), nullable=True),
    sa.Column('annotations', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_relative', sa.Boolean(), nullable=True),
    sa.Column('clipping', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('map_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studies_id'), 'studies', ['id'], unique=False)
    op.create_index(op.f('ix_studies_vendor'), 'studies', ['vendor'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('epmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('map_name', sa.String(), nullable=False),
    sa.Column('study_name', sa.String(), nullable=False),
    sa.Column('number_of_points', sa.Integer(), nullable=True),
    sa.Column('mesh_file', sa.String(), nullable=True),
    sa.Column('triangles', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('vertices', postgresql.ARRAY(sa.FLOAT()), nullable=True),
    sa.Column('triangle_areas', postgresql.ARRAY(sa.FLOAT()), nullable=True),
    sa.Column('is_vertex_at_edge', postgresql.ARRAY(sa.Boolean()), nullable=True),
    sa.Column('act_bip', postgresql.ARRAY(sa.FLOAT()), nullable=True),
    sa.Column('normals', postgresql.ARRAY(sa.FLOAT()), nullable=True),
    sa.Column('uni_imp_frc', postgresql.ARRAY(sa.FLOAT()), nullable=True),
    sa.Column('scalar_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epmaps_id'), 'epmaps', ['id'], unique=False)
    op.create_index(op.f('ix_epmaps_study_id'), 'epmaps', ['study_id'], unique=False)
    op.create_table('ep_map_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('point_index', sa.Integer(), nullable=False),
    sa.Column('carto_point_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.BigInteger(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('position_z', sa.Float(), nullable=True),
    sa.Column('woi_from', sa.Float(), nullable=True),
    sa.Column('woi_to', sa.Float(), nullable=True),
    sa.Column('reference_annotation', sa.Float(), nullable=True),
    sa.Column('map_annotation', sa.Float(), nullable=True),
    sa.Column('unipolar_voltage', sa.Float(), nullable=True),
    sa.Column('bipolar_voltage', sa.Float(), nullable=True),
    sa.Column('cs_positions', postgresql.ARRAY(sa.FLOAT()), nullable=True),
    sa.Column('magnetic20_positions', postgresql.ARRAY(sa.FLOAT()), nullable=True),
    sa.Column('roving_positions', postgresql.ARRAY(sa.FLOAT()), nullable=True),
    sa.Column('connector_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['epmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ep_map_points_id'), 'ep_map_points', ['id'], unique=False)
    op.create_index(op.f('ix_ep_map_points_map_id'), 'ep_map_points', ['map_id'], unique=False)
    op.create_index('ix_ep_map_points_map_point', 'ep_map_points', ['map_id', 'point_index'], unique=False)
    op.create_table('epmap_attributes',
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['epmaps.id'], ),
    sa.PrimaryKeyConstraint('map_id')
    )
    op.create_index('ix_epmap_attributes_attributes', 'epmap_attributes', ['attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_epmap_attributes_map_id'), 'epmap_attributes', ['map_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_epmap_attributes_map_id'), table_name='epmap_attributes')
    op.drop_index('ix_epmap_attributes_attributes', table_name='epmap_attributes', postgresql_using='gin')
    op.drop_table('epmap_attributes')
    op.drop_index('ix_ep_map_points_map_point', table_name='ep_map_points')
    op.drop_index(op.f('ix_ep_map_points_map_id'), table_name='ep_map_points')
    op.drop_index(op.f('ix_ep_map_points_id'), table_name='ep_map_points')
    op.drop_table('ep_map_points')
    op.drop_index(op.f('ix_epmaps_study_id'), table_name='epmaps')
    op.drop_index(op.f('ix_epmaps_id'), table_name='epmaps')
    op.drop_table('epmaps')
    op.drop_table('users')
    op.drop_index(op.f('ix_studies_vendor'), table_name='studies')
    op.drop_index(op.f('ix_studies_id'), table_name='studies')
    op.drop_table('studies')
    op.drop_table('reports')
    op.drop_table('colormaps')
    op.drop_index(op.f('ix_attribute_metadata_id'), table_name='attribute_metadata')
    op.drop_table('attribute_metadata')
    # ### end Alembic commands ###
