"""add placed_points table

Revision ID: 6f7abb350e3b
Revises: cc7318c9c1de
Create Date: 2026-07-12 00:31:52.708554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f7abb350e3b'
down_revision: Union[str, Sequence[str], None] = 'cc7318c9c1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placed_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('position', postgresql.ARRAY(sa.FLOAT()), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placed_points_id'), 'placed_points', ['id'], unique=False)
    op.create_index(op.f('ix_placed_points_study_id'), 'placed_points', ['study_id'], unique=False)
    op.create_index(op.f('ix_placed_points_type'), 'placed_points', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_placed_points_type'), table_name='placed_points')
    op.drop_index(op.f('ix_placed_points_study_id'), table_name='placed_points')
    op.drop_index(op.f('ix_placed_points_id'), table_name='placed_points')
    op.drop_table('placed_points')
    # ### end Alembic commands ###
