"""add measurement_points table

Revision ID: cc7318c9c1de
Revises: 61863fd599e4
Create Date: 2026-07-11 15:50:45.373249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc7318c9c1de'
down_revision: Union[str, Sequence[str], None] = '61863fd599e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('point_index', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('position', postgresql.ARRAY(sa.FLOAT()), nullable=True),
    sa.Column('measurements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('electrodes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['epmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_points_id'), 'measurement_points', ['id'], unique=False)
    op.create_index(op.f('ix_measurement_points_map_id'), 'measurement_points', ['map_id'], unique=False)
    op.create_index('ix_measurement_points_map_point', 'measurement_points', ['map_id', 'point_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_measurement_points_map_point', table_name='measurement_points')
    op.drop_index(op.f('ix_measurement_points_map_id'), table_name='measurement_points')
    op.drop_index(op.f('ix_measurement_points_id'), table_name='measurement_points')
    op.drop_table('measurement_points')
    # ### end Alembic commands ###
